In [1]:
import jax
from neurallogic import hard_not, hard_and, harden, neural_logic_net, harden_layer, primitives
from tests import test_mnist

2022-11-23 09:34:37.747733: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-11-23 09:34:37.747923: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-11-23 09:34:37.747941: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


In [ ]:
numpy.sum(numpy.array([1,2,3]), 0)

In [9]:
jax.numpy.mean(jax.numpy.array([[1,2,3],[4,5,6],[7,8,9]]), -1)

DeviceArray([2., 5., 8.], dtype=float32)

In [2]:
soft, hard, symbolic = neural_logic_net.net(test_mnist.nln)

In [3]:
mock_input = jax.numpy.ones([28, 28])
rng = jax.random.PRNGKey(0)
soft_weights = soft.init(rng, mock_input)
hard_weights = harden.hard_weights(soft_weights)

/workspaces/neural-logic/neurallogic/hard_or.py:95: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in asarray is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  x = jax.numpy.asarray(x, self.dtype)
/workspaces/neural-logic/neurallogic/hard_not.py:73: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in asarray is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  x = jax.numpy.asarray(x, self.dtype)


In [4]:
soft.apply(soft_weights, mock_input)

DeviceArray([198., 215., 208., 203., 213., 187., 201., 192., 191., 199.],            dtype=float32)

In [5]:
hard.apply(hard_weights, harden.harden(mock_input))

DeviceArray([198, 215, 208, 203, 213, 187, 201, 192, 191, 199], dtype=int32)

In [5]:
symbolic_weights = harden.symbolic_weights(soft_weights)
symbolic.apply(symbolic_weights, harden.harden(mock_input).tolist())

[198, 215, 208, 203, 213, 187, 201, 192, 191, 199]